-- Initialize the daily_play table in the local Postgres
CREATE TABLE IF NOT EXISTS public.daily_play (
    play_date       DATE PRIMARY KEY,
    maimai_play_count    INTEGER,
    chunithm_play_count  INTEGER,
    maimai_cumulative    INTEGER,
    chunithm_cumulative  INTEGER,
    maimai_rating        NUMERIC,
    chunithm_rating      NUMERIC,
    scrape_failed        BOOLEAN DEFAULT FALSE,
    failure_reason       TEXT
);

-- Japan play history is journal-derived and intentionally isolated from the
-- International scraper table above.  ONGEKI is measured in tracks, not plays.
-- BEGIN JAPAN_DAILY_PLAY
CREATE TABLE IF NOT EXISTS public.japan_daily_play (
    play_date                   DATE PRIMARY KEY,
    maimai_play_count           INTEGER NOT NULL CHECK (maimai_play_count >= 0),
    chunithm_play_count         INTEGER NOT NULL CHECK (chunithm_play_count >= 0),
    ongeki_track_count          INTEGER NOT NULL CHECK (ongeki_track_count >= 0),
    maimai_cumulative           INTEGER NOT NULL CHECK (maimai_cumulative >= 0),
    chunithm_cumulative         INTEGER NOT NULL CHECK (chunithm_cumulative >= 0),
    ongeki_cumulative_tracks    INTEGER NOT NULL CHECK (ongeki_cumulative_tracks >= 0),
    source                      TEXT NOT NULL DEFAULT 'obsidian_journal'
                                CHECK (source = 'obsidian_journal'),
    source_paths                TEXT[] NOT NULL CHECK (cardinality(source_paths) > 0),
    source_hashes               TEXT[] NOT NULL,
    inferred_games              TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    CHECK (cardinality(source_paths) = cardinality(source_hashes)),
    CHECK (inferred_games <@ ARRAY['maimai', 'chunithm', 'ongeki']::TEXT[]),
    CHECK (array_position(inferred_games, NULL) IS NULL),
    CHECK (maimai_play_count <= maimai_cumulative),
    CHECK (chunithm_play_count <= chunithm_cumulative),
    CHECK (ongeki_track_count <= ongeki_cumulative_tracks)
);

ALTER TABLE public.japan_daily_play
    ADD COLUMN IF NOT EXISTS inferred_games TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
-- END JAPAN_DAILY_PLAY

-- Per-song score snapshots (JSONB from chuumai-tools). scraped_at is naive
-- Asia/Bangkok wall-clock, matching daily_play.play_date semantics.
CREATE TABLE IF NOT EXISTS public.user_scores (
    id         SERIAL PRIMARY KEY,
    game       TEXT NOT NULL,
    scraped_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'Asia/Bangkok'),
    data       JSONB NOT NULL
);

-- Migrate legacy TIMESTAMPTZ column (and its old index) to naive BKK.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'user_scores'
          AND column_name = 'scraped_at'
          AND data_type = 'timestamp with time zone'
    ) THEN
        DROP INDEX IF EXISTS public.user_scores_game_day_bkk_key;
        ALTER TABLE public.user_scores
            ALTER COLUMN scraped_at TYPE TIMESTAMP
            USING (scraped_at AT TIME ZONE 'Asia/Bangkok');
        ALTER TABLE public.user_scores
            ALTER COLUMN scraped_at SET DEFAULT (NOW() AT TIME ZONE 'Asia/Bangkok');
        ALTER TABLE public.user_scores
            ALTER COLUMN scraped_at SET NOT NULL;
    END IF;
END $$;

-- Collapse same-day snapshots (keep newest per game per day) before
-- enforcing the unique index. Safe to re-run: once the index exists no
-- duplicates can be created.
DELETE FROM public.user_scores
WHERE id IN (
    SELECT id FROM (
        SELECT id,
               ROW_NUMBER() OVER (
                   PARTITION BY game, scraped_at::date
                   ORDER BY scraped_at DESC, id DESC
               ) AS rn
        FROM public.user_scores
    ) ranked
    WHERE rn > 1
);

CREATE UNIQUE INDEX IF NOT EXISTS user_scores_game_day_key
    ON public.user_scores (game, (scraped_at::date));

-- Latest rating image per game, generated by chuumai-tools.
-- Single row per game keeps storage bounded (~2 MB total).
CREATE TABLE IF NOT EXISTS public.user_rating_images (
    game         TEXT PRIMARY KEY,
    image_data   BYTEA NOT NULL,
    content_type TEXT NOT NULL DEFAULT 'image/webp',
    updated_at   TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'Asia/Bangkok')
);
